# Site wide configuration

title: "Hello...we're under the process of getting this up, keep watching this space"
description: "Coming Soon"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: 

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2015
  month: 12
  day: 10
  hour: 0
  minute: 0

# Site owner
owner:
  name:
  email:
  twitter:
  google-plus:
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
